const state={data:[],watch:new Set(JSON.parse(localStorage.getItem('radar-watch')||'[]')),hidden:new Set(JSON.parse(localStorage.getItem('radar-hide')||'[]')),watchOnly:false};
const $=id=>document.getElementById(id), esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem('radar-watch',JSON.stringify([...state.watch]));localStorage.setItem('radar-hide',JSON.stringify([...state.hidden]));}
function score(n){return `<span class="score ${n>=70?'high':n<40?'low':''}">${n}</span>`}
function options(id,values){$(id).insertAdjacentHTML('beforeend',[...values].sort().map(x=>`<option>${esc(x)}</option>`).join(''));}
function render(){let q=$('search').value.toLowerCase(), view=$('view').value, source=$('source').value, category=$('category').value, sort=$('sort').value;
 let a=state.data.filter(x=>!state.hidden.has(x.id)&&(!state.watchOnly||state.watch.has(x.id))&&(!source||x.sources.some(s=>s.source===source))&&(!category||x.category===category)&&(!q||(x.opportunity+x.summary+x.category+x.sources.map(s=>s.title).join(' ')).toLowerCase().includes(q)));
 if(view==='new')a=a.filter(x=>x.first_detected===new Date().toISOString().slice(0,10)); if(view==='early')a=a.filter(x=>x.lifecycle==='Very Early'); if(view==='growing')a=a.filter(x=>x.scores.momentum>=60); if(view==='evidence')a=a.filter(x=>x.scores.evidence>=55); if(view==='low-saturation')a=a.filter(x=>x.scores.saturation<=35);
 a.sort((x,y)=>sort==='newest'?y.first_detected.localeCompare(x.first_detected):y.scores[sort]-x.scores[sort]);
 $('rows').innerHTML=a.length?a.map(x=>`<tr data-id="${esc(x.id)}"><td><div class="title">${esc(x.opportunity)}</div><div class="sub">${esc(x.summary)}</div></td><td>${esc(x.category)}</td><td>${x.first_detected}</td><td>${x.mentions_today} / ${x.mentions_7d}</td><td>${x.source_count}</td><td>${score(x.scores.momentum)}</td><td>${score(x.scores.novelty)}</td><td>${score(x.scores.saturation)}</td><td>${score(x.scores.evidence)}</td><td>${score(x.scores.accessibility)}</td><td>${score(x.scores.opportunity)}</td><td><span class="badge">${esc(x.lifecycle)}</span></td><td><button class="star" title="Watchlist" data-star="${esc(x.id)}">${state.watch.has(x.id)?'★':'☆'}</button></td></tr>`).join(''):'<tr><td class="empty" colspan="13">No matching opportunities yet. Check the next nightly run or loosen the filters.</td></tr>';
 $('rows').querySelectorAll('tr[data-id]').forEach(row=>row.addEventListener('click',e=>{if(!e.target.dataset.star)detail(row.dataset.id)}));$('rows').querySelectorAll('[data-star]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();state.watch.has(b.dataset.star)?state.watch.delete(b.dataset.star):state.watch.add(b.dataset.star);save();render()}));
}
function detail(id){let x=state.data.find(o=>o.id===id);$('detail-content').innerHTML=`<p class="eyebrow">${esc(x.lifecycle)} · ${esc(x.category)}</p><h2>${esc(x.opportunity)}</h2><p>${esc(x.summary)}</p><div class="detail-grid"><section><h3>Why now</h3><p>${esc(x.why_now)}</p></section><section><h3>Evidence</h3><p>${esc(x.evidence_label)}. Treat individual claims as unverified until independently corroborated.</p></section><section><h3>Scorecard</h3><p>Novelty ${x.scores.novelty} · Momentum ${x.scores.momentum} · Evidence ${x.scores.evidence} · Saturation ${x.scores.saturation}</p></section><section><h3>Actions</h3><button id="watch-detail">${state.watch.has(id)?'Remove from watchlist':'Add to watchlist'}</button> <button id="hide-detail" class="secondary" style="color:var(--ink);border-color:var(--line)">Ignore</button></section></div><h3>Original discussions</h3>${x.sources.map(s=>`<a class="source-link" target="_blank" rel="noreferrer" href="${esc(s.url)}"><b>${esc(s.source)}</b> — ${esc(s.title)} <span class="sub">${esc(s.source_detail)}</span></a>`).join('')}`;$('detail').showModal();$('watch-detail').onclick=()=>{state.watch.has(id)?state.watch.delete(id):state.watch.add(id);save();$('detail').close();render()};$('hide-detail').onclick=()=>{state.hidden.add(id);save();$('detail').close();render()}}
async function init(){try{let d=await fetch('data/opportunities.json?'+Date.now()).then(r=>r.json());state.data=d.opportunities||[];$('status').textContent=`Updated ${new Date(d.generated_at).toLocaleString()} · ${d.raw_items_seen} raw discussions screened`;options('source',new Set(state.data.flatMap(x=>x.sources.map(s=>s.source))));options('category',new Set(state.data.map(x=>x.category)));let avg=state.data.length?Math.round(state.data.reduce((n,x)=>n+x.scores.opportunity,0)/state.data.length):0;$('summary').innerHTML=`<div class="metric"><b>${state.data.length}</b><span>Qualified signals</span></div><div class="metric"><b>${state.data.filter(x=>x.lifecycle==='Very Early').length}</b><span>Very early</span></div><div class="metric"><b>${state.data.filter(x=>x.scores.momentum>=60).length}</b><span>Accelerating</span></div><div class="metric"><b>${avg}</b><span>Average signal score</span></div>`;render()}catch(e){$('status').textContent='Data has not been generated yet. Run the collector once.';$('rows').innerHTML='<tr><td class="empty" colspan="13">Waiting for the first collection run.</td></tr>'}}
['search','view','source','category','sort'].forEach(id=>$(id).addEventListener('input',render));$('watch-only').onclick=()=>{state.watchOnly=!state.watchOnly;$('watch-only').textContent=state.watchOnly?'All signals':'Watchlist';render()};$('reset-local').onclick=()=>{state.watch.clear();state.hidden.clear();save();render()};$('.close').onclick=()=>$('detail').close();init();
